# Generated by Django 5.2.8 on 2025-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
